### ISSUE TITLE
native $$ delimited inner Class support needed for nested Interfaces

### ISSUE THREAD

**Issue by Cotton-Ben** [peter-lawrey/HugeCollections-OLD#16]
isolating this concern into its own separate issue.

3.0e RELEASE should ideally support  

```
DataValueClasses.newDirectReferece(InterfaceWithNestedInterface.class);

```

 invokes.

the 3.0e-SNAPSHOT fixes the GBP to $$ delimiter issue for long and integer on Mac OSX, and Fedora Linux.  However, the 3,0e-SNAPSHOT still does not empower the single test at 

https://github.com/Cotton-Ben/infinispan/tree/master/off-heap

to pass for the case =  BondVOInterface.class (nested interface on top of inner MarketPx interface).

Here is the current @Test result (NOTE: MarketPx$$native not being shown --  inner interface still delimited with GBP symbol):

```
[TestNG] Running:
  C:\Users\ben\.IdeaIC13\system\temp-testng-customsuite.xml

ISPN7 JCACHE DataContainer view of OpenHFT SHM is being created
OpenHFT SHMBuilder starting: /dev/shmSHM/bondVO.@t=1395489757714  entries=[NULL]
OpenHFT SHMBuilder done: /dev/shmSHM/bondVO.@t=1395489757714  entries=[{}]
ISPN7 JCACHE DataContainer created jcacheDataContainer=[org.infinispan.offheap.container.OffHeapDefaultDataContainer@2789eebb]
/org/infinispan/offheap/BondVOInterface$MarketPx£native.java:12: error: class MarketPx£native is public, should be declared in a file named MarketPx£native.java
public class MarketPx£native implements MarketPx, BytesMarshallable, Byteable, Copyable<org.infinispan.offheap.BondVOInterface$MarketPx> {
       ^
/org/infinispan/offheap/BondVOInterface$MarketPx£native.java:12: error: cannot find symbol
public class MarketPx£native implements MarketPx, BytesMarshallable, Byteable, Copyable<org.infinispan.offheap.BondVOInterface$MarketPx> {
                                        ^
  symbol: class MarketPx
/org/infinispan/offheap/BondVOInterface$MarketPx£native.java:12: error: cannot find symbol
public class MarketPx£native implements MarketPx, BytesMarshallable, Byteable, Copyable<org.infinispan.offheap.BondVOInterface$MarketPx> {
                                                                                                              ^
  symbol:   class BondVOInterface$MarketPx
  location: package org.infinispan.offheap
/org/infinispan/offheap/BondVOInterface$MarketPx£native.java:63: error: cannot find symbol
    public void copyFrom(org.infinispan.offheap.BondVOInterface$MarketPx from) {
                                               ^
  symbol:   class BondVOInterface$MarketPx
  location: package org.infinispan.offheap
/org/infinispan/offheap/BondVOInterface$MarketPx£native.java:113: error: cannot find symbol
        if (!(o instanceof MarketPx)) return false;
                           ^
  symbol:   class MarketPx
  location: class MarketPx£native
/org/infinispan/offheap/BondVOInterface$MarketPx£native.java:114: error: cannot find symbol
        MarketPx that = (MarketPx) o;
        ^
  symbol:   class MarketPx
  location: class MarketPx£native
/org/infinispan/offheap/BondVOInterface$MarketPx£native.java:114: error: cannot find symbol
        MarketPx that = (MarketPx) o;
                         ^
  symbol:   class MarketPx
  location: class MarketPx£native
java.lang.AssertionError: java.lang.ClassNotFoundException: org.infinispan.offheap.BondVOInterface$MarketPxÂ£native
    at net.openhft.lang.model.DataValueGenerator.acquireNativeClass(DataValueGenerator.java:315)
    at net.openhft.lang.model.DataValueGenerator.acquireNativeClass(DataValueGenerator.java:302)
    at net.openhft.lang.model.DataValueClassCache.directClassFor(DataValueClassCache.java:48)
    at net.openhft.lang.model.DataValueClassCache.newDirectReference(DataValueClassCache.java:37)
    at net.openhft.lang.model.DataValueClasses.newDirectReference(DataValueClasses.java:36)
    at org.infinispan.offheap.test.OffHeapDefaultDataContainerTest.testOpenHFTasOffHeapJcacheOperandProvider(OffHeapDefaultDataContainerTest.java:75)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at org.testng.TestRunner.privateRun(TestRunner.java:767)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
    at org.testng.TestNG.run(TestNG.java:1031)
    at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
    at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Caused by: java.lang.ClassNotFoundException: org.infinispan.offheap.BondVOInterface$MarketPxÂ£native
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at net.openhft.compiler.CachedCompiler.loadFromJava(CachedCompiler.java:108)
    at net.openhft.lang.model.DataValueGenerator.acquireNativeClass(DataValueGenerator.java:313)
    ... 35 more
7 errors

Process finished with exit code 0


```

**Comment by peter-lawrey** [comment]
This error can only mean there is still uses of £ in the code.

**Comment by ben--cotton** [comment]
So when Rob made this commit:  https://github.com/OpenHFT/Java-Lang/commit/1ca4e51c5af3378db6b4f659e93ae6516918efa5

I see where he clearly changed GBP to $$.  Did this affect both the HC and JL OpenHFT modules?  Do I have to do something in addition to

```
Ben

This should be fixed in the latest snapshot (and subsequent release):

  <groupId>net.openhft</groupId>
  <artifactId>collections</artifactId>
  <version>3.0e-SNAPSHOT</version>

please let me know if you still have any problems
```

?

i.e. do I need to also add a specific JL snapshot update dependency  to my Infinispan Fork's [off-heap] build module's pom.xml?

**Comment by Cotton-Ben** [comment]
Something is weird with my git account.  If this shows up 2x, I aplogize.

So when Rob made this commit: OpenHFT/Java-Lang@1ca4e51

I see where he clearly changed GBP to $$. Did this affect both the HC and JL OpenHFT modules? Do I have to do something in addition to

```
Ben

This should be fixed in the latest snapshot (and subsequent release):

  <groupId>net.openhft</groupId>
  <artifactId>collections</artifactId>
  <version>3.0e-SNAPSHOT</version>

please let me know if you still have any problems
?
```

i.e. do I need to also add a specific JL snapshot update dependency to my Infinispan Fork's [off-heap] build module's pom.xml?

**Comment by RobAustin** [comment]
> do I need to also add a specific JL snapshot update dependency to my Infinispan Fork's [off-heap] build module's pom.xml

Ben

As it's a snapshot, you will have to build the new "lang", and make sure it's pulling this version into your project.  

```
<artifactId>lang</artifactId>
<version>6.3.4-SNAPSHOT</version>
```

You should not have to add the dependency directly to your project as it will get transitated , but if you are specifying a version of lang in YOUR  dependency management section, please make sure it's 6.3.4-SNAPSHOT

Rob

**Comment by Cotton-Ben** [comment]
Thanks Rob,

Explicitly providing <version>6.3.4-SNAPSHOT</version> did the trick.  No more GBP v.$$ problems.

**Comment by RobAustin** [comment]
Cool
